import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#141b2b",
        "on-tertiary-fixed": "#07006c",
        "inverse-on-surface": "#edf0ff",
        "on-secondary-fixed-variant": "#003ea8",
        "surface-tint": "#535d7e",
        "primary-fixed-dim": "#bbc5eb",
        "tertiary-container": "#07006c",
        "error": "#ba1a1a",
        "inverse-surface": "#293040",
        "on-secondary-fixed": "#00174b",
        "tertiary-fixed-dim": "#c0c1ff",
        "on-primary-container": "#7883a6",
        "error-container": "#ffdad6",
        "outline-variant": "#c6c6ce",
        "surface-container-low": "#f1f3ff",
        "on-secondary-container": "#fefcff",
        "surface-bright": "#f9f9ff",
        "on-surface-variant": "#45464e",
        "surface-container-high": "#e1e8fd",
        "surface-container-highest": "#dce2f7",
        "background": "#f9f9ff",
        "secondary-fixed-dim": "#b4c5ff",
        "on-tertiary-container": "#7073ff",
        "on-primary-fixed": "#0f1a37",
        "primary": "#000000",
        "outline": "#76777e",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#141b2b",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#e1e0ff",
        "secondary-container": "#316bf3",
        "on-secondary": "#ffffff",
        "surface": "#f9f9ff",
        "secondary": "#0051d5",
        "on-tertiary-fixed-variant": "#2f2ebe",
        "on-primary-fixed-variant": "#3b4665",
        "surface-variant": "#dce2f7",
        "on-error": "#ffffff",
        "primary-fixed": "#dae2ff",
        "primary-container": "#0f1a37",
        "surface-dim": "#d3daef",
        "inverse-primary": "#bbc5eb",
        "tertiary": "#000000",
        "on-primary": "#ffffff",
        "surface-container": "#e9edff",
        "secondary-fixed": "#dbe1ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "stack-lg": "32px",
        "margin-desktop": "64px",
        "gutter": "24px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "margin-mobile": "20px",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-base": ["Inter", "sans-serif"],
        "mono-label": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        "display-lg-mobile": ["Inter", "sans-serif"],
        "display-lg": ["Inter", "sans-serif"],
      },
      fontSize: {
        "body-base": ["16px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "mono-label": ["13px", { lineHeight: "18px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", letterSpacing: "0em", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" }],
        "display-lg-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
      maxWidth: {
        "container-max": "1280px",
      },
    },
  },
  plugins: [],
};

export default config;
